### ISSUE TITLE
豆瓣FM有关于频度的反爬虫策略，限制每5秒打开一个新tab来抓呗

### ISSUE THREAD

**Issue by mywaiting** [loveunk/douban-favorite-music-parser#3]
RT

不能打开得太快啊！

另外，在同一个tab内可以直接插 js，直接请求Ajax 的分页接口就可以抓到数据啦！

比如这样 http://douban.fm/j/play_record?ck=XXXX&spbid=XXXX&type=liked&start=15

其实直接在 console 就可以抓数据了......

**Comment by loveunk** [comment]
哈哈，谢谢你的建议，不过我最近没时间改这个code 。如果你有空的话，欢迎提交代码进来～ :)

**Comment by mywaiting** [comment]
@loveunk 感觉最近懒得自己都看不下去了。我在 console 里面直接抓了出来了，几行JS的事情，懒得去折腾 chrome extension 了

**Comment by loveunk** [comment]
@mywaiting 如果方便，可以把你的那几行JS code copy在这里，也许可以帮到别的朋友 : )

**Comment by ae6623** [comment]
@mywaiting 歌单下载完毕之后，如何批量下载，有软件没。谢哥！在线等，急。
