### ISSUE TITLE
楼主，E音乐盒已经挂了，还有其他的下载工具没。

### ISSUE THREAD

**Issue by ae6623** [loveunk/douban-favorite-music-parser#4]
已经按照楼主的插件，完美下载了所有的歌单txt文档，非常赞！
不过，由于E音乐盒已经于2012年不再更新，想问下各位，有其他的导入歌名就可以进行下载的音乐工具么，谢谢。

QQ 43163707 再次感谢楼主！

**Comment by loveunk** [comment]
已经支持直接导出酷我列表，此列表可导入网易云音乐
